name: MattClegg
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d6cabe'
    - '#725b49'
    - '#90745c'
    - '#3a2d24'
  brandStrength: 0.8125
  lightness: 0.7575967153534293
  saturation: 0.5653337754774839
  rhythmicContrast: 0.5076580219902098
purpose: []
